# Generated by Django 2.2.6 on 2019-12-13 14:39

from django.db import migrations, models
import django.db.models.manager
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterModelManagers(
            name='students',
            managers=[
                ('stuObj2', django.db.models.manager.Manager()),
            ],
        ),
    ]
